# These are supported funding model platforms

github: [erdogant]
buy_me_a_coffee: erdogant
ko_fi: erdogant
custom: [https://erdogant.github.io/bnlearn/pages/html/Documentation.html]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
tidelift: #
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
