echo "Cleaning previous builds first.."
rm -rf dist
rm -rf build
rm -rf bnlearn.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf .pylint.d
rm -rf bnlearn/data/*.zip
rm -rf bnlearn/data/*.bif
rm -rf bnlearn/data/*.png
rm -rf bnlearn/data/*.txt
rm -rf bnlearn/data/*.json
rm -rf bnlearn/data/*.csv
rm -rf bnlearn/__pycache__
rm -rf bnlearn/helpers/__pycache__
rm -rf bnlearn/tests/__pycache__
rm -rf bnlearn/discretize/__pycache__
rm -rf bnlearn/bnlearn/*.pkl
rm -rf bnlearn/bnlearn/*.html
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf *.pkl
